import os

USE_GPU = True
USE_GPU_GLOBAL = True
NUM_GPU = 1
NUM_META_AGENT = 8
LR = 3e-5
GAMMA = 0.99
DECAY_STEP = 2e3
RESET_OPT = False
EVALUATE = True
CURRICULUM_LEARNING = False
INCREASE_DIFFICULTY = 2000
SUMMARY_WINDOW = 8
DEMON_RATE = 0.5
IL_DECAY = -1e-5  # -1e-6 700k decay 0.5, -1e-5 70k decay 0.5, -1e-4 7k decay 0.5
AGENTS_RANGE = (10, 20)
TASKS_RANGE = (20, 50)
COALITION_SIZE = 5
MAX_TIME = 100
EVAL_MAX_WAITING_TIME = 10
TRAIT_DIM = 1

# v0.1 dynamic coalition/task settings
TASK_ALPHA = 1.0
# Fixed beta for the first implementation (no sweep yet).
COALITION_BETA = 0.8
MODE_COST_TYPE = 'linear'  # 'linear' or 'quadratic'

# v0.1 reward weights
# Reward ratio follows: makespan : travel : wait : mode = 1.0 : 0.05 : 0.1 : 0.05
REWARD_W_MAKESPAN = 1.0
REWARD_W_TRAVEL = 0.05
REWARD_W_WAIT = 0.1
REWARD_W_MODE = 0.05

# v0.3 anti-oscillation constraints and dense reward shaping
ENABLE_COMMIT_LOCK = True
MIN_COMMIT_TIME = 2.0
ENABLE_QUORUM_PROTECT = True
SWITCH_PENALTY = 0.15
QUORUM_BREAK_PENALTY = 0.5
PAUSE_EVENT_PENALTY = 0.2
USE_DENSE_EVENT_REWARD = True
USE_POTENTIAL_SHAPING = True
POTENTIAL_SHAPING_COEF = 1.0

# v0.3 critic + GAE settings
USE_CRITIC = True
GAE_LAMBDA = 0.95
VALUE_COEF = 0.5
ENTROPY_COEF_START = 0.02
ENTROPY_COEF_END = 0.002
ENTROPY_DECAY_STEPS = 300000
MAX_GRAD_NORM = 1.0
CRITIC_INPUT_DIM = 16
CRITIC_HIDDEN_DIM = 128

FOLDER_NAME = 'REINFORCE'
model_path = os.getenv('DCMRTA_MODEL_PATH', f'model/{FOLDER_NAME}')
train_path = os.getenv('DCMRTA_TRAIN_PATH', f'train/{FOLDER_NAME}')
gifs_path = os.getenv('DCMRTA_GIFS_PATH', f'gifs/{FOLDER_NAME}')
LOAD_MODEL = False
SAVE_IMG = True
SAVE_IMG_GAP = 10000
WANDB_LOG = False

BATCH_SIZE = 1024
AGENT_INPUT_DIM = 6
TASK_INPUT_DIM = 5
EMBEDDING_DIM = 128
SAMPLE_SIZE = 200
PADDING_SIZE = 50
