AGENTS_RANGE: [10, 20]
AGENT_INPUT_DIM: 6
BATCH_SIZE: 1024
COALITION_BETA: 0.8
COALITION_SIZE: 5
CURRICULUM_LEARNING: false
DECAY_STEP: 2000.0
DEMON_RATE: 0.5
EMBEDDING_DIM: 128
EVALUATE: true
EVAL_MAX_WAITING_TIME: 10
FOLDER_NAME: "REINFORCE"
GAMMA: 1
GIT_COMMIT: "6af3096"
HOSTNAME: "autodl-container-74jt894l2h-9a38d0a2"
IL_DECAY: -1e-05
INCREASE_DIFFICULTY: 2000
LOAD_MODEL: false
LR: 1e-05
MAX_TIME: 100
MODE_COST_TYPE: "linear"
NUM_GPU: 1
NUM_META_AGENT: 8
PADDING_SIZE: 50
RESET_OPT: false
REWARD_W_MAKESPAN: 1.0
REWARD_W_MODE: 0.05
REWARD_W_TRAVEL: 0.05
REWARD_W_WAIT: 0.1
RUN_COMMENT: "manual_run"
RUN_DIR: "/root/DCMRTA/runs/20260224_142635_REINFORCE_baseline_manual_run"
RUN_NAME: "20260224_142635_REINFORCE_baseline_manual_run"
RUN_TAG: "baseline"
SAMPLE_SIZE: 200
SAVE_IMG: true
SAVE_IMG_GAP: 10000
START_TIME: "2026-02-24 14:26:39"
SUMMARY_WINDOW: 8
TASKS_RANGE: [20, 50]
TASK_ALPHA: 1.0
TASK_INPUT_DIM: 5
TRAIT_DIM: 1
USE_GPU: true
USE_GPU_GLOBAL: true
WANDB_LOG: false
gifs_path: "/root/DCMRTA/runs/20260224_142635_REINFORCE_baseline_manual_run/artifacts/gifs"
model_path: "/root/DCMRTA/runs/20260224_142635_REINFORCE_baseline_manual_run/model"
train_path: "/root/DCMRTA/runs/20260224_142635_REINFORCE_baseline_manual_run/train/tb"
